"""Utility modules for Dagster assets."""

from dagster_quickstart.utils.exceptions import (
    CSVValidationError,
    DataSourceValidationError,
    LookupTableError,
    MetaSeriesNotFoundError,
    CalculationError,
    DatabaseError,
    DatabaseQueryError,
    DatabaseInsertError,
    DatabaseUpdateError,
    RecordNotFoundError,
)
from dagster_quickstart.utils.constants import (
    LOOKUP_TABLE_COLUMNS,
    META_SERIES_REQUIRED_COLUMNS,
    DEFAULT_CSV_PATHS,
    NULL_VALUE_REPRESENTATION,
    LOOKUP_TABLE_PROCESSING_ORDER,
    DB_TABLES,
    DB_COLUMNS,
    CALCULATION_TYPES,
    DEFAULT_SMA_WINDOW,
    DEFAULT_WEIGHT_DIVISOR,
    QUERY_LIMIT_DEFAULT,
    QUERY_LIMIT_MAX,
)
from dagster_quickstart.utils.helpers import (
    safe_int,
    parse_data_source,
    validate_csv_columns,
    read_csv_safe,
    generate_date_range,
    load_series_data_from_clickhouse,
    get_or_validate_meta_series,
    create_calculation_log,
    update_calculation_log_on_success,
    update_calculation_log_on_error,
    is_empty_row,
)

__all__ = [
    # Exceptions
    "CSVValidationError",
    "DataSourceValidationError",
    "LookupTableError",
    "MetaSeriesNotFoundError",
    "CalculationError",
    "DatabaseError",
    "DatabaseQueryError",
    "DatabaseInsertError",
    "DatabaseUpdateError",
    "RecordNotFoundError",
    # Constants
    "LOOKUP_TABLE_COLUMNS",
    "META_SERIES_REQUIRED_COLUMNS",
    "DEFAULT_CSV_PATHS",
    "NULL_VALUE_REPRESENTATION",
    "LOOKUP_TABLE_PROCESSING_ORDER",
    "DB_TABLES",
    "DB_COLUMNS",
    "CALCULATION_TYPES",
    "DEFAULT_SMA_WINDOW",
    "DEFAULT_WEIGHT_DIVISOR",
    "QUERY_LIMIT_DEFAULT",
    "QUERY_LIMIT_MAX",
    # Helpers
    "safe_int",
    "parse_data_source",
    "validate_csv_columns",
    "read_csv_safe",
    "generate_date_range",
    "load_series_data_from_clickhouse",
    "get_or_validate_meta_series",
    "create_calculation_log",
    "update_calculation_log_on_success",
    "update_calculation_log_on_error",
    "is_empty_row",
]

